### ISSUE TITLE
0 FPS in Dungeons

### ISSUE THREAD

**Issue by princessbinas** [Greymerk/minecraft-roguelike#145]
I have been having massive issues with this mod in a multiplayer server I play on and in single player. The spawners in the dungeons are causing my game to drop to 0 FPS (I am using Optifine, BetterFPS, and TexFix with the lowest settings I can possibly use) very quickly due to the sheer numbers of mobs they churn out. Is it possible for you to make so we can edit the parts that cause severe lag to occur like how often and how many monsters each spawner produces. I really want to be able to fully explore these dungeons on my own.

**Comment by DChronosX** [comment]
Hello! First, I apologize for the long post... but want to give as much info as I can and make a request.... I back the OP's request as well.

This is the same thing happening to a 1.7.10 server I'm on, and after much testing, I've narrowed things down to this mod, the number of spawners, and specifically mobs spawning, or something about them spawning... though I think part of the issue is a bug found and fixed in later 1.8 versions of this mod having to do with not communicating mob despawning between server and client: https://github.com/Greymerk/minecraft-roguelike/issues/125 (which was stated to be an easy fix). Framerate will drop to about 10 FPS, sometimes as low as 2 FPS when inside these dungeons, or even with the dungeon chunks loaded if you had already been in the area long enough for the lag to begin, which is less than an hour.

First off, I just tested turning off that rogue spawner setting in the config, and where I'm at in my test that would quickly put me at 2-3 FPS, endlessly, I have now been there killing mobs for 20 minutes with only some lag, but with the sheer amount of monsters being spawned in, getting 20 FPS and still being very playable is reasonable.

Did a lot of testing and swapping between peaceful and any difficulty in single player as well... things run fine in peaceful... for awhile.... but it's like mobs are still spawned in the server side of things or something, regardless of being in peaceful, I don't know.  But as soon as you approach spawning distance of rooms with tons of spawners, especially in the final room that has like 10+ mob spawners alone, and some of the catacombs above it, even in peaceful mode, the entity count starts to skyrocket, and an "unspecified" entity causes the ticks in the Shift+F3 graphs to go from taking only about 14% of the CPU time to upwards of 88% or more.... and this unspecified entity ticks is 99% of it. 

Things will stay perfectly fine in peaceful mode for awhile until you get close enough to those rooms for spawners to work.... but in any mode where the mobs actually spawn, this shoots up immediately as soon as you're in the second floor down... but regardless if you approach the dungeons or not, simply being right there in any other difficulty except peaceful will cause the entity count to rise and cause the game to begin lagging within an hour of the server being reset.  Upon a server restart, everything clears up and things run perfectly smooth again until being in this area long enough for these mobs / phantom server mobs to build up.  Leaving the area does not fix it, either... the game will continue to lag endlessly until the next server restart.  The lag does diminish some when leaving the area, but it will not completely clear until then.  And approaching close enough for the dungeon chunks to be loaded makes the immense lag come back, as if the mobs never despawned, as I said above.  It appears as though they have on the client side, but does not act as such and more mobs spawn in.


I tried to look in the config files to see about limiting the number of mobs spawned, and / or spawners generated, just to see if I could quell this some through that, but there's no options for it... however, I just tested turning off that rogueSpawners setting in the config, and where I'm at in my tests that would quickly put me at 2-3 FPS, endlessly, I have now been there killing mobs for 20 minutes in the final room with only some lag, but with the sheer amount of monsters being spawned in, getting 20 FPS and still being very playable is reasonable. What's that setting actually do in the game differently than vanilla spawner metadata.. magic armor stuff? *shrug* I thought they did have magic armor before,  but after turning it off, they don't? I dunno.

Anyway, just reporting this, and I'd like to ask if you could update the 1.7.10 minecraft version of your very cool mod with the bug fixes in later versions... especially the one I referenced above where they mention the same issues we're having.  I'll ask in that bug's thread as well.  Please and thanks?

**Comment by Opalie** [comment]
Issue still present on latest version, for 1.12.2. It's not as bad as 0~3 FPS for me, but it's not playable after getting low enough in the dungeons. I think the issue is with the silverfish and cave spiders spawn. I know OP hasn't been present in more than a year, but I prefer leaving a comment if I can help for later on if they come back.
